version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/node:22.14.0
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: 'yarn install --frozen-lockfile'
      - run:
          name: "Build Vite"
          command: 'yarn run build'
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=1200"
          from: dist
          to: 's3://potentiaali/'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
orbs:
  aws-s3: circleci/aws-s3@2.0.0
